apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-allow-frontend
  namespace: cloudcart
spec:
  podSelector:
    matchLabels:
      app: cloudcart-backend

  policyTypes:
  - Ingress

  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: cloudcart-frontend