apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcart-backend
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: cloudcart-backend

  template:
    metadata:
      labels:
        app: cloudcart-backend

    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}