apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcart-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: cloudcart-frontend

  template:
    metadata:
      labels:
        app: cloudcart-frontend

    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}